services:
  ollama:
    image: ollama/ollama:latest
    pull_policy: always
    restart: unless-stopped
    tty: true
    ipc: host
    ports:
      - "11434:11434"
    volumes:
      - "${OLLAMA_ROOT:-$HOME/.ollama/ollama}:/root/.ollama"
    environment:
      - CPU_FALLBACK=true
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    networks:
      - ollama-net
    privileged: false
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    ipc: host
    command: []
    environment:
      - OLLAMA_BASE_URLS=http://ollama:11434
    depends_on:
      - ollama
    ports:
      - "3050:8080"
    volumes:
      - "${OPEN_WEBUI_ROOT:-$HOME/.ollama/open-webui}:/app/backend/data"
    networks:
      - ollama-net
    extra_hosts:
      - host.docker.internal:host-gateway
    privileged: false
    hostname: ollama-open-webui

networks:
  ollama-net:
    driver: bridge
    external: false
